#!/bin/bash
# Execute this to package up evolvotron as a .tar.gz

VER=`./VERSION`
APP_DIR=$PWD

# Clone into a temporary directory to get a clean project.
cd /tmp
git clone $APP_DIR evolvotron-$VER

tar czf evolvotron-$VER.tar.gz --exclude .git evolvotron-$VER
