#!/bin/sh

# Script to echo the current version number.
# The number is also hardcoded in these files:
#   libevolvotron/common.h
#   evolvotron.spec

# NB If you edit this, "make distclean" and then rebuild (./BUILD) as there is no dependency checking

echo "0.8.1"
