#!/bin/sh

# Script to echo the current version number.
# THIS IS THE ONLY PLACE A VERSION NUMBER SHOULD BE SPECIFIED

# NB If you edit this, make clean and rebuild as there is no dependency checking

echo "0.1.1"
