#ifndef _libevolvotron_register_all_functions_h_
#define _libevolvotron_register_all_functions_h_

/* NB The corresponding .cpp is AUTO GENERATED by update_register_all_functions script */

class FunctionRegistry;

extern void register_all_functions(FunctionRegistry&);

#endif
