.TH EVOLVOTRON_RENDER 1 "25 Feb 2004" "www.timday.com" "Evolvotron"

.SH NAME
evolvotron_render \- Render an evolvotron function tree to an image.

.SH SYNOPSIS
evolvotron_render
[\-f 
.I <frames>
]
[\-j]
[\-m
.I <multisample>
]
[\-s
.I <width>
.I <height>
]
[\-spheremap]
[\-v]
.I <imagefile.[png|ppm]>
<
.I <file.xml>

.SH DESCRIPTION

.B evolvotron_render 
reads an evolvotron image function from it's
standard input and renders it to the file specified
(suffix determines type, defaults to ppm if not recognised).

Image functions can be obtained by saving them from the
evolvotron applicaiton, or using evolvotron_mutate.

See the evolvotron manual (accessible from the evolvotron
application's Help menu) for more information on image functions.

.SH COMMAND-LINE OPTIONS

.TP 0.5i
.B -j
Enable sample jittering.

.TP 0.5i
.B \-m
.I <multisample>
Enables antialiased rendering.
This specifies the size of the sub-pixel sampling grid,
so 1 provides the default one-sample-per-pixel behaviour,
while 4 provides 16 samples per pixel on a 4x4 grid.
Unlike the main evolvotron application, there is no upper limit,
but of course rendering time increases as the square of this number.

.TP 0.5i
.B \-s
.I <width>
.I <height>
Specify resolution of output image.
Defaults to 512 512.

.TP 0.5i
.B \-v
Verbose mode; useful for monitoring progress of large renders.

.TP 0.5i
.B \-f
.I <frames>
Generates multi-frame animations.  .fnnnnnn is inserted into
the specified filename (before the filetype suffix, if any).
You can use this on functions which weren't evolved in animation mode, but there's
no guarantee they have any interesting time/z variation.

.TP 0.5i
.B \-spheremap
Create a spheremap instead of a planar texture.

.SH EXAMPLES

evolvotron_mutate \-g > function.xml

evolvotron_render \-v \-s 2048 2048 function.ppm < function.xml

.SH AUTHOR
.B evolvotron_render
was written by Tim Day (www.timday.com) and is released
under the conditions of the GNU General Public License.
See the file LICENSE supplied with the source code for details.

.SH SEE ALSO

evolvotron(1), evolvotron_mutate(1)
