.TH EVOLVOTRON 1 "24 Feb 2004" "www.timday.com" "Evolvotron"

.SH NAME
evolvotron \- Creates generative art by an interactive evolutionary process.

.SH SYNOPSIS
evolvotron
[Qt options]
[options]

.SH DESCRIPTION

.B evolvotron
is interactive "generative art" software to evolve
images/textures/patterns through an iterative process of random
mutation and user-selection driven evolution.
Basically it displays a grid of random images; you click
on one you like and the rest of the grid is refilled with
variants of the one you picked.

This man page describes only the command line options.
A more complete manual fully describing usage via the application's GUI
is accessible from the application's "Help" menu once it is running.

.SH GENERAL OPTIONS

.TP 0.5i
.B \-\-autocool | \-a
Enable autocooling by default.

.TP 0.5i
.B \-\-cols | \-c
.I cols
Number of columns in image display grid (defaults to 6).

.TP 0.5i
.B \-\-fullscreen | \-F
Start in "fullscreen" mode (window manager permitting).
[Press "Esc" key to revert to normal windowed mode].

.TP 0.5i
.B \-\-help | \-h
Display a summary of command-line options and exit.

.TP 0.5i
.B \-\-jitter | \-j
Enable sample jittering.

.TP 0.5i
.B \-\-multisample | \-m
.I multisample
Enables antialiased rendering.
Valid values are 1,2,3,4.
This specifies the size of the sub-pixel sampling grid,
so 1 provides the default one-sample-per-pixel behaviour,
while 4 provides 16 samples per pixel on a 4x4 grid.

.TP
.B \-\-menuhide | \-M
Start with menu and status bars supressed.
[Press "Esc" key to display them].

.TP 0.5i
.B \-\-rows | \-r
.I rows
Number of rows in image display grid (defaults to 5).

.TP 0.5i
.B \-spheremap | \-s
Create spheremaps instead of planar textures.
NB The middle-mouse adjustments will not behave as expected in this mode.

.SH ANIMATION OPTIONS

.TP 0.5i
.B \-\-frames | \-f
.I frames
Number of frames to animate (defaults to 1 i.e no animaton)

.TP 0.5i
.B \-\-linear | \-l
Vary z linearly with time rather than sinusoidally over animation period.

.TP 0.5i
.B \-\-fps | \-s
.I framerate
Specify rate at which animations are displayed
(as an integer number of frames per second).
Defaults to 8.

.SH POWER-USER / DEBUG OPTIONS

UPDATE BELOW HERE

.TP 0.5i
.B \-E
Use a separate thread pool for computing enlargements.
Using this option ensures computation of enlargements continue to make
some progress even while the main grid is being actively worked on.
However, this will be at the expense of main grid rendering performance.
Without this option, enlargements' final high-resolution renderings are
invariably lower priority than computation for images in the main
grid.
See also the \-N option to control the priority of threads in this pool.

.TP 0.5i
.B \-n
.I <niceness>
Niceness of compute threads relative to the main application thread (defaults to 4).

.TP 0.5i
.B \-N
.I <enlargement niceness>
Niceness relative to the main application thread of compute threads dealing with enlargements (defaults to 4 more than grid niceness).
Only effective in conjunction with -E option.

.TP 0.5i
.B \-t
.I <threads>
Number of compute threads (defaults to number of CPUs)

.TP 0.5i
.I <QtOptions>
The Qt GUI system recognizes an number of additional options
(for example, standard X11 things like -geometry <width>x<height>).

.TP 0.5i
.B \-D
Debug mode.
Currently simply sets function weightings so virtually all function nodes are FunctionNoiseOneChannel.
This is really only useful to developers in conjunction with the -x/-X options.

.TP 0.5i
.B \-v
Verbose mode.
Probably most useful for getting a list of supported
function names for use with the -x/-X options.

.TP 0.5i
.B \-x
.I <functionname>
Force a specific function type to be used at the top level of
all new image function trees (wrapped by random colour and
spatial transforms).
This can also be controlled from the "Favourite" dialog.

.TP 0.5i
.B \-X
.I <functionname>
Similar to
.B \-x
but with no wrapper functions.

.SH EXAMPLES

evolvotron \-x FunctionSpiralLinear

evolvotron \-X FunctionKaleidoscope

.SH AUTHOR
.B evolvotron
was written by Tim Day (www.timday.com) and is released
under the conditions of the GNU General Public License.
For further details see the application's "About" dialog
(accessible from the "Help" menu),
or the file LICENSE supplied with the source code.

.SH SEE ALSO

evolvotron_mutate(1), evolvotron_render(1)
